### ISSUE TITLE
The repository 'http://archive.canonical.com/ubuntu kinetic Release' does not have a Release file.

### ISSUE THREAD

**Issue by yasersakkaf** [browserless/chrome#3245]
**Describe the bug**
This image, which is currently the `browserless/chrome:latest`, gives me the error `The repository 'http://archive.canonical.com/ubuntu kinetic Release' does not have a Release file.` for the command `RUN apt-get update -y` in my Dockerfile

**To Reproduce**
Create a Dockerfile and input the following contents

```
FROM browserless/chrome:latest
USER root
RUN apt-get update -y

```

**Expected behavior**
The docker image should be created without any such errors

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.3.1 (a)
 - Browser: Chrome 114

**Comment by joelgriffith** [comment]
Confirmed. Looking into this, apologies

**Comment by jagilley** [comment]
Seconded, I'm getting the same error both when running locally and on a server.

I'm no Docker expert, but might it be downstream of this line in the base Dockerfile?
```
RUN apt-get -y -qq install software-properties-common && \
  apt-add-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner"
```

**Comment by jagilley** [comment]
@yasersakkaf did you make any progress on debugging this?

**Comment by joelgriffith** [comment]
Have you tried latest? We've switched ubuntu release versions since this issue came up originally so the problem should hopefully be resolved now

**Comment by nextrevision** [comment]
I can confirm that this is still an issue with the latest tag of the `browserless/chrome` image:
```
$ docker run --rm -it --entrypoint /bin/bash -u root browserless/chrome
root@0a6a500ab388:/usr/src/app# apt update
Get:1 http://security.ubuntu.com/ubuntu lunar-security InRelease [109 kB]
Ign:2 http://archive.canonical.com/ubuntu lunar InRelease
Err:3 http://archive.canonical.com/ubuntu lunar Release
  404  Not Found [IP: 91.189.91.15 80]
Get:4 http://archive.ubuntu.com/ubuntu lunar InRelease [267 kB]
Get:5 http://security.ubuntu.com/ubuntu lunar-security/restricted amd64 Packages [451 kB]
Get:6 http://archive.ubuntu.com/ubuntu lunar-updates InRelease [109 kB]
Get:7 http://archive.ubuntu.com/ubuntu lunar-backports InRelease [99.8 kB]
Get:8 http://security.ubuntu.com/ubuntu lunar-security/multiverse amd64 Packages [7179 B]
Get:9 http://security.ubuntu.com/ubuntu lunar-security/universe amd64 Packages [905 kB]
Get:10 http://archive.ubuntu.com/ubuntu lunar/universe amd64 Packages [18.7 MB]
Get:11 http://security.ubuntu.com/ubuntu lunar-security/main amd64 Packages [422 kB]
Get:12 http://archive.ubuntu.com/ubuntu lunar/multiverse amd64 Packages [289 kB]
Get:13 http://archive.ubuntu.com/ubuntu lunar/main amd64 Packages [1797 kB]
Get:14 http://archive.ubuntu.com/ubuntu lunar/restricted amd64 Packages [181 kB]
Get:15 http://archive.ubuntu.com/ubuntu lunar-updates/main amd64 Packages [547 kB]
Get:16 http://archive.ubuntu.com/ubuntu lunar-updates/multiverse amd64 Packages [7179 B]
Get:17 http://archive.ubuntu.com/ubuntu lunar-updates/universe amd64 Packages [1009 kB]
Get:18 http://archive.ubuntu.com/ubuntu lunar-updates/restricted amd64 Packages [451 kB]
Get:19 http://archive.ubuntu.com/ubuntu lunar-backports/universe amd64 Packages [4208 B]
Reading package lists... Done
E: The repository 'http://archive.canonical.com/ubuntu lunar Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@0a6a500ab388:/usr/src/app# echo $?
100
root@0a6a500ab388:/usr/src/app# rm /etc/apt/sources.list.d/archive_uri-http_archive_canonical_com_ubuntu-lunar.list
root@0a6a500ab388:/usr/src/app# apt update
Hit:1 http://archive.ubuntu.com/ubuntu lunar InRelease
Hit:2 http://security.ubuntu.com/ubuntu lunar-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu lunar-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu lunar-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
```

Relevant docker image details:
```
$ docker inspect browserless/chrome
...
        "Id": "sha256:1ea073536389e883bd6d9955b71cea8c9619ca1bdd6f7bd3e73b022b9a583601",
        "RepoTags": [
            "browserless/chrome:latest"
        ],
        "RepoDigests": [
            "browserless/chrome@sha256:06d9772e88084bf835a23f63962a2d960b07b274ac2ac75a57db7d38b0f95834"
        ],
```

**Comment by joelgriffith** [comment]
Thanks for the logs. We'll take a look and see whats going on...

**Comment by nextrevision** [comment]
Someone's going to have to keep me honest here, but I think the partner archive repo is being added, but never used since there's no `apt update` or similar refresh after it is added: https://github.com/browserless/chrome/blob/master/base/Dockerfile#L18.

Unless add-apt-repository performs a background `apt update`, but I would expect to see a failure.

**Comment by joelgriffith** [comment]
Great find! Looking into that now.

**Comment by nextrevision** [comment]
Can confirm this issue is no longer present. Thanks!
